// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace DownloadPolicyXML
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WinButton uICloseButton = this.UIDownloadWizardBrightWindow.UICloseWindow.UICloseButton;
            WinTitleBar uIDownloadWizardBrightTitleBar = this.UIDownloadWizardBrightWindow.UIDownloadWizardBrightTitleBar;
            WinButton uICloseButton1 = this.UIDownloadWizardBrightWindow.UIDownloadWizardBrightTitleBar.UICloseButton;
            #endregion

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(25, 11));

            // Click 'Download Wizard ( Brighthouse Financial )' title bar
            Mouse.Click(uIDownloadWizardBrightTitleBar, new Point(431, 11));

            // Click 'Close' button
            Mouse.Click(uICloseButton1, new Point(9, 4));
        }
        
        #region Properties
        public UIDownloadWizardBrightWindow UIDownloadWizardBrightWindow
        {
            get
            {
                if ((this.mUIDownloadWizardBrightWindow == null))
                {
                    this.mUIDownloadWizardBrightWindow = new UIDownloadWizardBrightWindow();
                }
                return this.mUIDownloadWizardBrightWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIDownloadWizardBrightWindow mUIDownloadWizardBrightWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDownloadWizardBrightWindow : WinWindow
    {
        
        public UIDownloadWizardBrightWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Download Wizard ( Brighthouse Financial )";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Download Wizard ( Brighthouse Financial )");
            #endregion
        }
        
        #region Properties
        public UICloseWindow UICloseWindow
        {
            get
            {
                if ((this.mUICloseWindow == null))
                {
                    this.mUICloseWindow = new UICloseWindow(this);
                }
                return this.mUICloseWindow;
            }
        }
        
        public UIDownloadWizardBrightTitleBar UIDownloadWizardBrightTitleBar
        {
            get
            {
                if ((this.mUIDownloadWizardBrightTitleBar == null))
                {
                    this.mUIDownloadWizardBrightTitleBar = new UIDownloadWizardBrightTitleBar(this);
                }
                return this.mUIDownloadWizardBrightTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UICloseWindow mUICloseWindow;
        
        private UIDownloadWizardBrightTitleBar mUIDownloadWizardBrightTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UICloseWindow : WinWindow
    {
        
        public UICloseWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnCancel";
            this.WindowTitles.Add("Download Wizard ( Brighthouse Financial )");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Download Wizard ( Brighthouse Financial )");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDownloadWizardBrightTitleBar : WinTitleBar
    {
        
        public UIDownloadWizardBrightTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Download Wizard ( Brighthouse Financial )");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Download Wizard ( Brighthouse Financial )");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
}
